version: '3.9'

services:

  mongo:
    restart: always
    logging:
      driver: journald

  mongo-exporter:
    restart: always
    logging:
      driver: journald

  injective-core:
    restart: always
    logging:
      driver: journald

  indexer-exchange-import:
    logging:
      driver: journald

  indexer-exchange-api:
    restart: always
    logging:
      driver: journald

  indexer-exchange-process:
    restart: always
    logging:
      driver: journald
